task:
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      image: freebsd-11-2-release-amd64
  env:
    OS: FreeBSD
  install_script: pkg install -y gmake
  script: mount; env; gmake all
